services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sequelize-db
      MYSQL_USER: sequelize
      MYSQL_PASSWORD: 1234
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - '3306:3306'
  myadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - '8080:80'
volumes:
  db-volume:
